#pragma once

#define USE_SERIAL

#define MASTER_LEFT

#define MOUSEKEY_DELAY 3
#define MOUSEKEY_INTERVAL 3
#define MOUSEKEY_MAX_SPEED 3
#define MOUSEKEY_TIME_TO_MAX 10
#define MOUSEKEY_WHEEL_MAX_SPEED 1
#define MOUSEKEY_WHEEL_TIME_TO_MAX 3
